#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 21 16:34:32 2017

@author: jordansorensen
"""


#Given a text file (I have uploaded the file to the documents section) you need to provide the following functionality:
#Average grade for a student: Given an id of a student you show on the console the average grade for all the courses that student took
#Average grade for a course: Given the name of a course, you show on the console the average grade of all the students that took that course
#Average grade for all students: You show on the console the average grade for all the students in the file
#The implementation of this program needs to fulfill the MVC design pattern (with the Model taking care of the translation between the data source and the Controller, the Controller taking care of the rules/functionality of the system and the View that takes care of the User Interface.

#The program needs to execute an infinite loop to capture the user input and then show on the console the output related to this command.#

f = open("downloads/StudentFile.txt","r")

